### ISSUE TITLE
It is in rust

### ISSUE THREAD

**Issue by Lmello1** [Bendi11/rwr#1]
Hi good programmer,

I am writing to tell you of a critical bug I have found in your code. Unfortunately i have found that it is written in rust, This is of course a huge flaw and should be fixed as fast as possible. Please fix

Thanks,
C++

**Comment by Bendi11** [comment]
Hi,

Okay, I'll walk you through this. Let's prepare ourselves for a very intense usage of your two braincells. First, we're going to open the *main repository page* using a tool called *github*. Next, we're going to click on the folder named **src** by using your mouse cursor to move the icon onto the folder's name. Still with me? Okay, let's do the same thing, but now click on the file named *main.c*. Do you notice something? What is it? That's right, it's written in C YOU INEPT CRETIN
